### ISSUE TITLE
Elevation script returning TypeError: undefined "_container"

### ISSUE THREAD

**Issue by simplicitywebdesign** [altrdev/hugo-leaflet#13]
The map itself shows up fine, but the track does not. My console is showing the following issue:

```
Uncaught TypeError: Cannot read properties of undefined (reading '_container')
    at i._addToChartDiv (leaflet.elevation.js:628:38)
    at i.addTo (leaflet.elevation.js:182:18)
    at drawTrack (leaflet.hugo.js:62:56)
```
I have tried for a few weeks now to nail it down but I just don't have the JS abilities to debug it. I'm almost certain I'm doing something stupid here but cannot figure it out.

Anybody else come across this?

**Comment by charlesepaillard** [comment]
Hi @simplicitywebdesign I have the same problem on my side - showing maps and adding markers is all good. However I have the very same issue and error showing gpx.

**Comment by charlesepaillard** [comment]
using debugger: L.control.elevation(opts.elevationControl.options).addTo(leafletMapsObj[trackOpts.mapId]) returns an error
because leafletMapsObj[trackOpts.mapId] is "undefined"
main reason is that leafletMapsObj is an empty dictionary
![Capture](https://github.com/altrdev/hugo-leaflet/assets/7326398/66a1727e-36f7-4107-a272-fb7097501bf2)

**Comment by charlesepaillard** [comment]
ok, I understand the problem: drawTrack has to be called AFTER createMap.
